name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_TAG: "latest"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: echoback-node
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build and push"
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/laica-lunasys/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
